apiVersion: batch/v1
kind: Job
metadata:
  name: openbmc${BUILD_ID}-${target}
  namespace: ${namespace}
  labels:
    app: openbmc
    stage: build
spec:
  template:
    metadata:
      name: ${podname}
      labels:
        target: ${target}
    spec:
      nodeSelector:
        worker: \"true\"
        arch: ${ARCH}
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: ${hclaim}
      - name: sscdir
        persistentVolumeClaim:
          claimName: ${sclaim}
      - name: obmccache
        persistentVolumeClaim:
          claimName: ${oclaim}
      restartPolicy: Never
      hostNetwork: True
      containers:
      - image: ${imgname}
        name: builder
        command: [\"${WORKSPACE}/build.sh\"]
        workingDir: ${HOME}
        env:
        - name: WORKSPACE
          value: ${WORKSPACE}
        - name: obmcdir
          value: ${obmcdir}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: home
          mountPath: ${HOME}
        - name: sscdir
          mountPath: ${sscdir}
        - name: obmccache
          mountPath: ${obmcdir}
      imagePullSecrets:
      - name: ${imgplsec}
