apiVersion: batch/v1
kind: Job
metadata:
  name: openbmc${BUILD_ID}-${target}
  namespace: ${namespace}
  labels:
    app: openbmc
    stage: build
spec:
  template:
    metadata:
      name: ${podname}
      labels:
        target: ${target}
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: ${ARCH}
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: ${wclaim}
      - name: sscdir
        persistentVolumeClaim:
          claimName: ${sclaim}
      restartPolicy: Never
      hostNetwork: True
      containers:
      - image: ${imgname}
        name: builder
        command: [\"${WORKSPACE}/build.sh\"]
        workingDir: ${HOME}
        env:
        - name: WORKSPACE
          value: ${WORKSPACE}
        - name: builddir
          value: ${builddir}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: workspace
          mountPath: ${WORKSPACE}
        - name: sscdir
          mountPath: ${sscdir}
      imagePullSecrets:
      - name: ${imgplsec}
