apiVersion: v1
kind: Pod
metadata:
  name: ${podname}
  namespace: ${namespace}
spec:
  nodeSelector:
    beta.kubernetes.io/arch: ${ARCH}
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: ${wclaim}
  - name: qemudir
    persistentVolumeClaim:
      claimName: ${qclaim}
  restartPolicy: Never
  hostNetwork: True
  containers:
  - image: ${imgname}
    name: builder
    command: [\"${WORKSPACE}/build.sh\"]
    workingDir: ${HOME}
    env:
    - name: WORKSPACE
      value: ${WORKSPACE}
    - name: qemudir
      value: ${qemudir}
    volumeMounts:
    - name: workspace
      mountPath: ${WORKSPACE}
    - name: qemudir
      mountPath: ${qemudir}
  imagePullSecrets:
  - name: ${imgplsec}
