apiVersion: batch/v1
kind: Job
metadata:
  name: ${podname}
  namespace: ${namespace}
  labels:
    app: qemu
    stage: build
spec:
  template:
    metadata:
      name: ${podname}
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: ${ARCH}
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: ${hclaim}
      - name: qemudir
        persistentVolumeClaim:
          claimName: ${qclaim}
      restartPolicy: Never
      hostNetwork: True
      containers:
      - image: ${imgname}
        name: builder
        command: [\"${WORKSPACE}/build.sh\"]
        workingDir: ${HOME}
        env:
        - name: WORKSPACE
          value: ${WORKSPACE}
        - name: qemudir
          value: ${qemudir}
        volumeMounts:
        - name: home
          mountPath: ${HOME}
        - name: qemudir
          mountPath: ${qemudir}
      imagePullSecrets:
      - name: ${imgplsec}
